################################################################
################ MIGRATION SERVICE PROPERTIES ##################
################################################################
migration:
  modelfolder: /development/sosym-edelta-tool-demo/repository