################################################################
################ MIGRATION SERVICE PROPERTIES ##################
################################################################
migration:
  modelfolder: C:\\development\\sosym-edelta-tool-demo\\repository